# Generated by Django 4.1 on 2022-08-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('apdated_ad', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos/Y%/m%/d%/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
